name: Build Docker Images for docker-baseimage-cloud9

on:
  workflow_dispatch:

jobs:
  build-ubuntu20:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (Ubuntu 20.04)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker-baseimage-cloud9-ubuntu20/Dockerfile
          push: true
          tags: gvoze32/cloud9-base:focal

  build-ubuntu22:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (Ubuntu 22.04)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker-baseimage-cloud9-ubuntu22/Dockerfile
          push: true
          tags: gvoze32/gvoze32/cloud9-base:jammy
