name: Image

on:
  workflow_dispatch:

jobs:
  build-ubuntu20:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (Ubuntu 20.04)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-focal
          push: true
          tags: gimanelizabeth899/cloud9:focal

  build-ubuntu22:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (Ubuntu 22.04)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-jammy
          push: true
          tags: gimanelizabeth899/cloud9:jammy

  build-ubuntu24:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (Ubuntu 24.04)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-noble
          push: true
          tags: gimanelizabeth899/cloud9:noble

  build-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (Ubuntu Latest)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-noble
          push: true
          tags: gimanelizabeth899/cloud9:latest
